services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anarkia41
      - POSTGRES_DB=pagui
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  backend:
    build: 
      context: ./backend
    ports:
      - "5000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:anarkia41@postgres:5432/pagui"
      JWT_SECRET: "cambiar_por_secreto_seguro"
      JWT_EXPIRATION: "24h"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000

volumes:
  postgres_data: 