# Stage 1: Builder
FROM node:22 AS builder
WORKDIR /usr/src/app
ARG VITE_API_URL
# ENV VITE_API_URL ${VITE_API_URL} || https://oe-api.databol.org/v1
ENV VITE_API_URL https://oe-api.databol.org/v1

# Copia los archivos necesarios para la construcción
COPY package.json bun.lock ./
RUN npm install

# Copia el resto del código fuente
COPY . .

# Construye el proyecto
RUN echo "Starting build process..."
RUN npm run build
RUN echo "Build process completed."

# Stage 2: Release
FROM oven/bun:1 AS release
WORKDIR /usr/src/app
ENV VITE_API_URL https://oe-api.databol.org/v1

# Copia solo los archivos generados por el proceso de construcción
COPY --from=builder /usr/src/app/build ./build

# Expone el puerto (ajusta según tu aplicación)
EXPOSE 3000/tcp

# Ejecuta la aplicación
USER bun
ENTRYPOINT [ "bun", "./build/index.js" ]