name: Publish page

on:
  push:
    branches:
      - main
    paths:
      - 'page/**'
      - '.github/workflows/publish-page.yml'
      - '!**/readme.md'
      - '!**/.env'
      - '!page/android/**'
      - '!page/ios/**'
  pull_request:
    branches:
      - main
    paths:
      - 'page/**'
      - '.github/workflows/publish-page.yml'
      - '!**/readme.md'
      - '!**/.env'
      - '!page/android/**'
      - '!page/ios/**'
env:
  VITE_API_URL: https://oe-api.databol.org/v1

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/pagui-page
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name == 'push' || (github.event.pull_request.merged == true && github.event.pull_request.state == 'closed')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: github.event_name == 'push' || (github.event.pull_request.merged == true && github.event.pull_request.state == 'closed')
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:page"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: VITE_API_URL=${{ env.VITE_API_URL }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/pagui-page-buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/pagui-page-buildcache